In [1]:
### Libraries Used Tensorflow> 2.0  and keras
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
### Vocabulary size
voc_size=10000


In [4]:
# One hot encoding
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8976, 3606, 6330, 5884], [8976, 3606, 6330, 762], [8976, 5265, 6330, 9965], [1969, 2267, 9014, 7412, 8846], [1969, 2267, 9014, 7412, 2720], [4005, 8976, 9366, 6330, 2173], [7149, 4295, 6355, 7412]]


In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np


In [7]:
# Padding sequences
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8976 3606 6330 5884]
 [   0    0    0    0 8976 3606 6330  762]
 [   0    0    0    0 8976 5265 6330 9965]
 [   0    0    0 1969 2267 9014 7412 8846]
 [   0    0    0 1969 2267 9014 7412 2720]
 [   0    0    0 4005 8976 9366 6330 2173]
 [   0    0    0    0 7149 4295 6355 7412]]


In [8]:
# Dimnesions
dim=10

In [9]:
# Creating a model and adding embedding layer
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [10]:
# Vectors
print(model.predict(embedded_docs))

[[[ 6.64405897e-03 -4.86977585e-02 -3.47793922e-02  9.87298414e-03
   -4.14581075e-02  3.18514146e-02  6.95585087e-03 -4.62007895e-02
   -2.86645647e-02  1.01415738e-02]
  [ 6.64405897e-03 -4.86977585e-02 -3.47793922e-02  9.87298414e-03
   -4.14581075e-02  3.18514146e-02  6.95585087e-03 -4.62007895e-02
   -2.86645647e-02  1.01415738e-02]
  [ 6.64405897e-03 -4.86977585e-02 -3.47793922e-02  9.87298414e-03
   -4.14581075e-02  3.18514146e-02  6.95585087e-03 -4.62007895e-02
   -2.86645647e-02  1.01415738e-02]
  [ 6.64405897e-03 -4.86977585e-02 -3.47793922e-02  9.87298414e-03
   -4.14581075e-02  3.18514146e-02  6.95585087e-03 -4.62007895e-02
   -2.86645647e-02  1.01415738e-02]
  [ 7.21155480e-03 -2.92553902e-02 -3.20996530e-02  3.85530330e-02
    3.72684635e-02  2.11360194e-02  4.18595560e-02  6.87426329e-03
    1.97370164e-02 -2.85310876e-02]
  [ 4.99429591e-02 -2.80639175e-02  2.75930874e-02 -3.61732133e-02
   -4.97569330e-02  2.02845410e-03  1.63497664e-02 -2.39967946e-02
    4.27034833e-

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0, 8976, 3606, 6330, 5884], dtype=int32)

In [12]:
print(model.predict(embedded_docs)[0])

[[ 0.00664406 -0.04869776 -0.03477939  0.00987298 -0.04145811  0.03185141
   0.00695585 -0.04620079 -0.02866456  0.01014157]
 [ 0.00664406 -0.04869776 -0.03477939  0.00987298 -0.04145811  0.03185141
   0.00695585 -0.04620079 -0.02866456  0.01014157]
 [ 0.00664406 -0.04869776 -0.03477939  0.00987298 -0.04145811  0.03185141
   0.00695585 -0.04620079 -0.02866456  0.01014157]
 [ 0.00664406 -0.04869776 -0.03477939  0.00987298 -0.04145811  0.03185141
   0.00695585 -0.04620079 -0.02866456  0.01014157]
 [ 0.00721155 -0.02925539 -0.03209965  0.03855303  0.03726846  0.02113602
   0.04185956  0.00687426  0.01973702 -0.02853109]
 [ 0.04994296 -0.02806392  0.02759309 -0.03617321 -0.04975693  0.00202845
   0.01634977 -0.02399679  0.04270348  0.04221297]
 [ 0.04104848  0.0228806  -0.02953686  0.0176642   0.0337841  -0.01802419
  -0.01017829  0.01467845  0.0480834   0.01446975]
 [-0.01079404 -0.02761657 -0.02098463 -0.02292798 -0.0134699   0.01095955
  -0.03291887  0.00544351  0.04477474  0.02764336]]